/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "timer.h"

uint32_t start;
uint32_t stop;

int main(void)
{
	/* Initial System Clock */
	system_clock_initial();

	/*Initial TIM3 for Delay Function*/
	timer5_init();

	RCC->AHB1ENR |= (1UL << 8);
	GPIOI->MODER |= (1UL << 2);
	GPIOI->OSPEEDR |= (2UL << 2);

	while(1)
	{
		GPIOI->BSRR |= (1U << 1);
		start = TIM5->CNT;
		delay_millis(1000);

		GPIOI->BSRR |= (1U << 17);
		start = TIM5->CNT;
		delay_millis(1000);

	}
}
